### ISSUE TITLE
Use curl instead of dig

### ISSUE THREAD

**Issue by benjiprod** [brianpcurran/gandi-automatic-dns#9]
For a better compatibilty with "nutty OS", you can use : 
`curl ipinfo.io/ip`
instead of dig.

**Comment by brianpcurran** [comment]
Things seem to be getting worse as far as inter-operability of DNS-related tools. Some OSs are moving to Unbound and shipping with drill instead of dig, some have removed nslookup, etc. I think the best solution will be to add a flag to specify a custom command that returns IP address information, and leave a somewhat sensible default (dig and OpenDNS).
